### ISSUE TITLE
Script unrecognized

### ISSUE THREAD

**Issue by rllola** [ShibeTechnology/dogecoin-spv-gui#24]
When syncing finding this error. This is from the spv node module. We are incorrectly parsing a transaction script.

```
webpack://nodegui-experiment/./node_modules/dogecoin-spv/src/wallet/utils.js?:196
    throw new Error('Script is not pay-to-pubkey-hash standard.')
          ^

Error: Script is not pay-to-pubkey-hash standard.
    at extractPubkeyHashFromP2PKH (webpack://nodegui-experiment/./node_modules/dogecoin-spv/src/wallet/utils.js?:196:11)
    at Wallet.extractPubkeyHashFromP2PKH (webpack://nodegui-experiment/./node_modules/dogecoin-spv/src/wallet/wallet.js?:107:12)
    at getHistory (webpack://nodegui-experiment/./src/app.js?:103:53)

Node.js v18.12.1
```

**Comment by patricklodder** [comment]
Do you know which block this occurred on?

**Comment by rllola** [comment]
No :sweat_smile: 

I should probably log the actual transaction in the error message. I am able to reproduce it so I will do that asap.

**Comment by rllola** [comment]
However I can already tell that the error is coming from here : https://github.com/ShibeTechnology/dogecoin-spv-node/blob/main/src/wallet/utils.js#L212

I had a really simplistic approach to detect script. It needs to be improved.
